apiVersion: v2
appVersion: "0.4.3"
description: A Kinesis Locaal Helm chart for Kubernetes
kubeVersion: ">= 1.21"
name: kinesis
type: application
version: 0.4.3

keywords:
  - kinesis
  - aws
  - local
  - kubernetes

maintainers:
  - name: Said Sef
    email: saidsef@gmail.com

sources:
  - https://github.com/saidsef/aws-kinesis-local.git
